language: android  
jdk: oraclejdk7
cache: false
sudo: required

env:
  global:
    - MALLOC_ARENA_MAX=2

notifications:
  email: true

android:  
  components:
    # for update build tools
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-android-support

before_install:  
  - chmod +x gradlew
  - chmod +x deploy.sh

script:  
  - ./gradlew assembleRelease -PdisablePreDex --info
before_deploy:
  - ./deploy.sh

deploy:  
  provider: releases
  api_key:
    api_key:
    secure: wifs3kkICwPtxd+OEoNMABi8IUl2VrMZslnP/oXuBA53NkrmQW9Mh2zXOCAh5P5sZMnD017AMBkHGzyDMKqI/XTFZxMDwWSighJs+HSVmhUZ/t4jpmEKZjfn/q50SlrFvSqiw9dltFwjynT+CRuIHW07ng0nfwyT3JXeyJeQImDlPOfHA7H2DgGnXxI72sjk1rhFtaPRT66vj3BQ2FmbM4Puo/eddwxdW/jXxOpLUx8oSUkENwGL2+70Cqv/00AZk+0gklZNqGRiwcjJrMkpEFaP0AV/ruJHqL9/G0baLqh8I/IBTZ8DnGv9hG4cxizmdyOBo0Q6xYmAGXvTf1gAn3voShsxA/SsHsjNDW2Wh6WZOLtg48cEydLHKpjz0Dffiq2mSbuTl5DO8qmv882udm441xHqz7RaAlvvCnSzHEMUo84flOgBAbdPtma+yiSgPHUcOq8f5opCM+ymrjfEjapw756UaQTaHp6shrqRKihIogWDgg8NzSEfrKTZSjTZpQAQPg7axqkQtlQhP8jg1d6pEjMIcWOJ7WFh1lhFCRDFTXvZppnpH88w679s3g7CWk3kR5Cg20zvnPznHBiqsFRktYy2O5EJM0pXOIRZtRla+M95cG6367wo6o/19R75QQKEACcLVvDbf0S7N96qV3U5EZwvdgqd6ZAK2FYMV/Q=
  file: "app/build/outputs/apk/zhihu.apk"
  skip_cleanup: true
  on:
    tags: true