language: android  
jdk: oraclejdk7
cache: false
sudo: required

env:
  global:
    - MALLOC_ARENA_MAX=2

notifications:
  email: true

android:  
  components:
    # for update build tools
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-android-support

before_install:  
  - chmod +x gradlew

script:  
  - ./gradlew assembleRelease -PdisablePreDex --info
before_deploy:  
  - sh deploy.sh

deploy:  
  provider: releases
  api_key: "9736ac63ffcc8aa654543dee348bfaf3b424fcb5"
  file: app/build/outputs/apk/zhihu.apk
  skip_cleanup: true
  on:
    tags: true